site_name: AUMB Handbook
site_description: Auburn University Marching Band Handbook 2026-2027

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate
    - search.highlight
    - search.suggest
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default  # Changed from auburn-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate    # Changed from auburn-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/auburn.css  # Ensure this path is relative to the 'docs' folder

markdown_extensions:
  - toc:
      permalink: true
      permalink_title: "Link to this section"
      toc_depth: 3
  - pymdownx.caption
  - attr_list
  - md_in_html
  - abbr

plugins:
  - search:
      lang: en
